name: app python

on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Teste com pytest
        run: |
          pytest  --cov --cov-report=term-missing
